packages:
  - "configs/tsconfig"
  - "configs/prettier-config"
  - "configs/eslint-config"
  - "configs/stylelint-config"
  - "packages/highlight"
  - "packages/papyrus"
  - "packages/papyrus/docs"
  - "packages/esthetic/docs"
  - "packages/esthetic"
  - "packages/schema"
  - "packages/specs"
  - "packages/parser"
  - "packages/server"
  - "packages/vscode"
  - "packages/moloko"
  - "packages/ava"
  - "packages/types"
